### ISSUE TITLE
forge not working

### ISSUE THREAD

**Issue by Wonkiest29** [xmdhs/gomclauncher#35]
./gml-linux -run 1.12.2-forge-14.23.5.2859 -username Wonkiest29
Verifying game core
Completed
Verifying library files
Completed
Verifying resource files
Completed
Verifying extracted natives library
retry 0: Seems to be a network issue, retrying https://download.mcbbs.net/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar get: HttpGet: Get "https://download.mcbbs.net/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar": tls: failed to verify certificate: x509: certificate is valid for *.cdn.myqcloud.com, *.2144.cn, *.2144.com, *.4399.com, *.5054399.com, *.58cdn.com.cn, *.danmu.com, *.dianping.com, *.dpfile.com, *.ffnews.cn, *.file.myqcloud.com, *.flash.2144.com, *.flash.cn, *.image.myqcloud.com, *.img4399.com, *.meituan.net, *.mykeeta.net, *.sogoucdn.com, *.uniqlo.cn, *.vip.cdngot.com, *.vod.myqcloud.com, *.vod2.myqcloud.com, *.wanyabox.com, *.zhongcheng818.com, *.zservey.net, cdn.myqcloud.com, nitrome.com.4399.com, www.miniclip.com.4399pk.com, xpdl999.aiwan4399.com, not download.mcbbs.net

**Comment by Wonkiest29** [comment]
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
panic: Run115: launcher1155.Launcher115: exit status 1

goroutine 1 [running]:
github.com/xmdhs/gomclauncher/flag.(*Flag).Arun(0xc000196000)
        github.com/xmdhs/gomclauncher/flag/run.go:73 +0x685
main.main()
        github.com/xmdhs/gomclauncher/main.go:86 +0x33f

**Comment by Wonkiest29** [comment]
```sh
 ./gml-linux -run 1.12.2-forge-14.23.5.2859 -username 1 -log -javapath "/usr/lib/jvm/liberica-jdk-8-full/bin/java"
```
fixed
