### ISSUE TITLE
微软账户登录时，弹出窗口在随机的时间自动关闭并报错

### ISSUE THREAD

**Issue by happyme531** [xmdhs/gomclauncher#5]
rt

```
.\gml-windows.exe -ms -run 1.12.2-forge1.12.2-14.23.4.2705 -email 2302004040@qq.com
panic: MsLogin: getCode: Getcode: ErrChromeWasClose

goroutine 1 [running]:
github.com/xmdhs/gomclauncher/flag.msLogincheakErr(0x1548ac0, 0xc000310020)
        github.com/xmdhs/gomclauncher/flag/mslogin.go:67 +0x351
github.com/xmdhs/gomclauncher/flag.(*Flag).MsLogin(0xc000162000)
        github.com/xmdhs/gomclauncher/flag/mslogin.go:36 +0x598
main.main()
        command-line-arguments/main.go:61 +0x497
```

**Comment by xmdhs** [comment]
我这里似乎是正常的。

能否告知下你使用的 edge 版本，以及若不是 88 版本的话，更新到 88 后是否依然如此。

[5.zip](https://github.com/xmdhs/gomclauncher/files/5873884/5.zip)
如果依然如此，可以试试用命令行打开这个程序，然后登录下账户，看下返回的内容是什么。这个是默认使用 chrome 来显示登录界面的。

**Comment by happyme531** [comment]
似乎重启电脑后问题不在发生了.....
这里我的gml启动器显示的登录界面是chromium的窗口,chromium版本是 84.0.4147.105

**Comment by xmdhs** [comment]
那现在也可以正常的用微软账号登录了吗。那么在观察一下吧。

**Comment by happyme531** [comment]
...........在经过一段时间以后又发现了这个问题  

在Ubuntu 20.10，chromium 88.0.4324.96下测试也有同样的问题  
现象:弹出窗口在随机的时间自动关闭  

```
/gml-linux  -ms  -independent=false -ram=8192 -run 1.12.2-forge1.12.2-14.23.4.2705 -email 2302004040@qq.com
panic: MsLogin: getCode: Getcode: ErrChromeWasClose

goroutine 1 [running]:
github.com/xmdhs/gomclauncher/flag.msLogincheakErr(0x7ce980, 0xc0003552a0)
	github.com/xmdhs/gomclauncher/flag/mslogin.go:67 +0x351
github.com/xmdhs/gomclauncher/flag.(*Flag).MsLogin(0xc000152000)
	github.com/xmdhs/gomclauncher/flag/mslogin.go:29 +0x547
main.main()
	command-line-arguments/main.go:61 +0x497
```

**Comment by happyme531** [comment]
*经过反复测试，msauth程序没有这个问题！*

**Comment by xmdhs** [comment]
找到原因了。

我修改了这个项目 https://github.com/zserge/lorca ，把其中的 websocket 库换成了另一个，并补充了心跳方面的代码。

不过没有想到 chrome 不会相应发送的 ping，所以最后的表现就是 60 秒后没收到回应，就关闭了浏览器了。

**Comment by xmdhs** [comment]
麻烦你试试这里底下 Artifacts 中的程序，看看是否被解决了。
https://github.com/xmdhs/gomclauncher/actions/runs/514227642

**Comment by happyme531** [comment]
问题已解决
